server:
  port: 8080

spring:
  datasource:
    # hikari连接池配置
    hikari:
      auto-commit: true
      maximum-pool-size: 20
      minimum-idle: 5
    # 数据库基础信息配置
    url: jdbc:mysql://101.43.195.41:3306/book_store?useUnicode=true&characterEncoding=gbk&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: indexwan123
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    hikari:
      sql:
        Statement: debug